#!/usr/bin/env bash
# Configure your domain zone.

domain="$1"
subdomain="$2"

if [ "$#" -eq 2 ]; then
    record=$(dig "$subdomain.$domain" |  awk 'NR==13 { print $4 }')
    ip=$(dig "$subdomain.$domain" | awk 'NR==13 { print $5 }')
    echo "The subdomain '$2' is a '$record' record and points to '$ip'"
else
    record=$(dig www."$domain" |  awk 'NR==13 { print $4 }')
    ip=$(dig www."$domain" | awk 'NR==13 { print $5 }')
    echo "The subdomain www is a '$record' record and points to '$ip'"
    record=$(dig lb-01."$domain" |  awk 'NR==13 { print $4 }')
    ip=$(dig lb-01."$domain" | awk 'NR==13 { print $5 }')
    echo "The subdomain lb-01 is a '$record' record and points to '$ip'"
    record=$(dig web-01."$domain" |  awk 'NR==13 { print $4 }')
    ip=$(dig web-01."$domain" | awk 'NR==13 { print $5 }')
    echo "The subdomain web-01 is a '$record' record and points to '$ip'"
    record=$(dig web-02."$domain" |  awk 'NR==13 { print $4 }')
    ip=$(dig web-02."$domain" | awk 'NR==13 { print $5 }')
    echo "The subdomain web-02 is a '$record' record and points to '$ip'"
fi

