#!/usr/bin/env bash
# Script that redirects /redirect_me and restart nginx
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
config_file="/etc/nginx/sites-available/default"

content_to_add="server_name _;\n\n\tlocation = /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sed -i "s,server_name _;,$content_to_add," "$config_file"
service nginx restart
