#!/usr/bin/env bash
# Script that Configure  Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

service nginx start
config_file="/etc/nginx/sites-available/default"

content_to_add="server_name _;\n\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sed -i "s,server_name _;,$content_to_add," "$config_file"
service nginx restart
