#!/usr/bin/env bash
# This script pings an IP address 5 times passed as an argument

if [ "$#" -eq 1 ]; then
    ping -c 5 "$1"
elif [ "$#" -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
