#!/usr/bin/env bash
# This script Manages 'manage_my_process'.

if [ "$1" = "start" ]; then
    bash ./manage_my_process &
    echo "$$" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
    pid=$(lsof -t "./manage_my_process")
    kill "$pid"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
    pid=$(lsof -t "./manage_my_process")
    kill "$pid"
    rm /var/run/my_process.pid
    bash ./manage_my_process &
    echo "$$" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
