#!/usr/bin/env bash
# This script is displaying The content of the /etc/passwd file
#Where only the part of the username, user id and Home directory 
#path for the user is displayed 
file="/etc/passwd"
while read -r line; do
    echo "$line" | cut -d ':' -f 1,3,6
done < "$file"
