#!/usr/bin/env bash
# This script is displaying The content of the /etc/passwd file
# Whit a specific format using while IFS=:
file="/etc/passwd"
while IFS=: read -r username password uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < "$file"
