#!/usr/bin/env bash
# This script configures an Ubuntu server
# localhost resolves to 127.0.0.2.
# facebook.com resolves to 8.8.8.8.

old_content="^127.0.0.1\s+localhost"
new_content="127.0.0.2       localhost"
file="/etc/hosts"

sed -i "s/$old_content/$new_content/g" $file
echo "8.8.8.8       facebook.com" >> $file
